### ISSUE TITLE
Need to Manually Run Matter's activate.sh Each Time I Open Terminal in VSCode (CON-241)

### ISSUE THREAD

**Issue by mriksman** [espressif/esp-matter#142]
I have set up an environment in VSCode using the following steps
1. Install WSL
2. Install Docker Desktop
3. Install VSCode
4. Install ESP-IDF Extension
5. Use ESP-IDF Extension to create a New Project
6. Edit the Dockerfile to include stuff for Matter

```
FROM espressif/idf:v4.4.2
<snip>
ENV PATH=/opt/qemu/bin:${PATH}

#############################
# Additional lines for Matter installation
# https://docs.espressif.com/projects/esp-matter/en/main/esp32/developing.html

# Prerequisites for Matter
RUN : \
  && apt-get update \
  && apt-get install -y \
  git \
  gcc \
  g++ \
  pkg-config \
  libssl-dev \
  libdbus-1-dev \
  libglib2.0-dev \
  libavahi-client-dev \
  ninja-build \
  python3-venv \
  python3-dev \
  python3-pip \
  unzip \
  libgirepository1.0-dev \
  libcairo2-dev \
  libreadline-dev \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/* \
  && : # last line

ARG ESP_MATTER_CLONE_URL=https://github.com/espressif/esp-matter.git

# perform a shallow clone
RUN git clone --depth 1 $ESP_MATTER_CLONE_URL $IDF_TOOLS_PATH/esp-matter && \
	cd $IDF_TOOLS_PATH/esp-matter && \
    git submodule update --init --depth=1 && \
    ./connectedhomeip/connectedhomeip/scripts/checkout_submodules.py --platform esp32 --shallow

# run Matter setup and build host tools and python dependencies for mfg_tool
RUN cd $IDF_TOOLS_PATH/esp-matter && \
    ./install.sh

# ** note: we may need to modify the entrypoint.sh file below to include the esp-matter export.sh
RUN echo "source /opt/esp/esp-matter/export.sh > /dev/null 2>&1" >> ~/.bashrc

#############################
# Back to orginal Dockerfile
```

Everything seems to build OK.

I then copy the `light` example in to my `/workspaces` folder (the project workspace in VSCode) and perform a Build.

I get the following error

```
[96/97] Generating binary image from built executable
esptool.py v3.3.2-dev
Creating esp32 image...
Merged 1 ELF section
Successfully created esp32 image.
Generated /workspaces/build/bootloader/bootloader.bin
[97/97] cd /workspaces/build/bootloader/esp-idf/esptool_py && /opt/esp/python_env/idf4.4_py3.8_env/bin/python /opt/esp/idf/components/partition_table/check_sizes.py --offset 0xc000 bootloader 0x1000 /workspaces/build/bootloader/bootloader.bin
Bootloader binary size 0x6330 bytes. 0x4cd0 bytes (44%) free.
[667/1312] Performing build step for 'chip_gn'
FAILED: esp-idf/chip/chip_gn-prefix/src/chip_gn-stamp/chip_gn-build esp-idf/chip/lib/libCHIP.a /workspaces/build/esp-idf/chip/chip_gn-prefix/src/chip_gn-stamp/chip_gn-build /workspaces/build/esp-idf/chip/lib/libCHIP.a 
cd /workspaces/build/esp-idf/chip && ninja esp32

<snip>

[46/729] ACTION //third_party/connectedhomeip/src/controller/data_model:data_model_codegen_codegen(//third_party/connectedhomeip/config/esp32/toolchain:esp32)
FAILED: gen/third_party/connectedhomeip/src/controller/data_model/app/PluginApplicationCallbacks.h gen/third_party/connectedhomeip/src/controller/data_model/app/callback-stub.cpp 
python ../../../../opt/esp/esp-matter/connectedhomeip/connectedhomeip/config/esp32/third_party/connectedhomeip/third_party/pigweed/repo/pw_build/py/pw_build/python_runner.py --gn-root ../../../../opt/esp/esp-matter/connectedhomeip/connectedhomeip/config/esp32/ --current-path ../../../../opt/esp/esp-matter/connectedhomeip/connectedhomeip/config/esp32/third_party/connectedhomeip/src/controller/data_model --default-toolchain=//third_party/connectedhomeip/config/esp32/toolchain:esp32 --current-toolchain=//third_party/connectedhomeip/config/esp32/toolchain:esp32 --capture-output --python-dep-list-files gen/third_party/connectedhomeip/src/controller/data_model/data_model_codegen_codegen_metadata_path_list.txt -- ../../../../opt/esp/esp-matter/connectedhomeip/connectedhomeip/config/esp32/third_party/connectedhomeip/scripts/codegen.py --generator cpp-app --output-dir gen/third_party/connectedhomeip/src/controller/data_model --expected-outputs gen/third_party/connectedhomeip/src/controller/data_model/data_model_codegen.expected.outputs ../../../../opt/esp/esp-matter/connectedhomeip/connectedhomeip/config/esp32/third_party/connectedhomeip/src/controller/data_model/controller-clusters.matter
Traceback (most recent call last):
  File "../../../../opt/esp/esp-matter/connectedhomeip/connectedhomeip/config/esp32/third_party/connectedhomeip/scripts/codegen.py", line 28, in <module>
    from idl.matter_idl_parser import CreateParser
  File "/opt/esp/esp-matter/connectedhomeip/connectedhomeip/scripts/idl/matter_idl_parser.py", line 7, in <module>
    from lark import Lark
ModuleNotFoundError: No module named 'lark'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../../opt/esp/esp-matter/connectedhomeip/connectedhomeip/config/esp32/third_party/connectedhomeip/scripts/codegen.py", line 32, in <module>
    from idl.matter_idl_parser import CreateParser
  File "/opt/esp/esp-matter/connectedhomeip/connectedhomeip/scripts/idl/matter_idl_parser.py", line 7, in <module>
    from lark import Lark
ModuleNotFoundError: No module named 'lark'

<snip>

ninja: build stopped: subcommand failed.
[668/1312] Linking C static library esp-idf/app_update/libapp_update.a
ninja: build stopped: subcommand failed.
```

**Comment by mriksman** [comment]
Possibly the Matter `requirements.txt` wasn't run?
https://github.com/project-chip/connectedhomeip/blob/19c8ea42b4f4af2669643b758caa4cf412cfee69/scripts/requirements.txt#L69-L71
I ran `pip install lark` and the next error I got was for `stringcase`

So something wrong with my Dockerfile, or with the `./install.sh` in `esp-matter`.

**Comment by mriksman** [comment]
There are other 'issues' as well with VSCode and Dev Containers.

When I run the Build command from the Activity bar (the little icon that looks like a cylinder), it errors with 
```
-- Found Git: /usr/bin/git (found version "2.25.1") 
CMake Error at /opt/esp/esp-matter/device_hal/device/m5stack/esp_matter_device.cmake:3 (message):
  please set esp32 as the IDF_TARGET using 'idf.py set-target esp32'
Call Stack (most recent call first):
  CMakeLists.txt:32 (include)
```

But in a new Bash terminal, I have already run `idf.py set-target esp32c3`, and `idf.py build` runs fine.

Someone needs to explain how VSCode, linux Containers and the environment variables are behaving. I bet it is a simple fix once I understand how each of these windows are loading their environments.

**Comment by shubhamdp** [comment]
@mriksman sorry for the late turn around!

> ModuleNotFoundError: No module named 'lark'

This has been fixed with 350dc6ae8b011b1e29070797daa55100840b3fbf

> \# run Matter setup and build host tools and python dependencies for mfg_tool
> RUN cd $IDF_TOOLS_PATH/esp-matter && \
>     ./install.sh
>
Before running `install.sh` please add `source $IDF_PATH/export.sh`, this would install the `lark` in IDF python environment preventing the `lark` error.


> My `~/.bashrc` has the following at the end
> 
> ```
> source /opt/esp/esp-matter/export.sh > /dev/null 2>&1
> source /opt/esp/idf/export.sh > /dev/null 2>&1
> ```

Sourcing sequence may be problem here, you are expected to source `esp-idf/export.sh` first and then `esp-matter/export.sh`

**Comment by dhrishi** [comment]
@mriksman Can you please try this out and close the issue if it works as expected

**Comment by mriksman** [comment]
> @mriksman Can you please try this out and close the issue if it works as expected

I'm working abroad at the moment, and I don't have much download data. I have it on my 'to-do' list for when I return home; about 2 weeks. Can we leave it open for 2 weeks, and I'll test when I am home and report back?

Thanks.

**Comment by dhrishi** [comment]
>Can we leave it open for 2 weeks, and I'll test when I am home and report back?

Yes, definitely. Not a problem

**Comment by mriksman** [comment]
Hi,

- I started a new project from ESP IDF Extension, and selected 'Sample Project'
- I assume `FROM espressif/idf` will get the `latest`, so I modify the line to be `FROM espressif/idf:v4.4.3`
- I add the following _after_ `RUN echo "source /opt/esp/idf/export.sh > /dev/null 2>&1" >> ~/.bashrc` (**as per your comment**)
```
#############################
# Additional lines for Matter installation
# https://docs.espressif.com/projects/esp-matter/en/main/esp32/developing.html

# Prerequisites for Matter
RUN : \
  && apt-get update \
  && apt-get install -y \
  git \
  gcc \
  g++ \
  pkg-config \
  libssl-dev \
  libdbus-1-dev \
  libglib2.0-dev \
  libavahi-client-dev \
  ninja-build \
  python3-venv \
  python3-dev \
  python3-pip \
  unzip \
  libgirepository1.0-dev \
  libcairo2-dev \
  libreadline-dev \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/* \
  && : # last line

ARG ESP_MATTER_CLONE_URL=https://github.com/espressif/esp-matter.git

# perform a shallow clone
RUN git clone --depth 1 $ESP_MATTER_CLONE_URL $IDF_TOOLS_PATH/esp-matter && \
	cd $IDF_TOOLS_PATH/esp-matter && \
    git submodule update --init --depth=1 && \
    ./connectedhomeip/connectedhomeip/scripts/checkout_submodules.py --platform esp32 --shallow

# run Matter setup and build host tools and python dependencies for mfg_tool
```
Modified this to include ` . $IDF_PATH/export.sh && \` **as per your comment**.
```
RUN cd $IDF_TOOLS_PATH/esp-matter && \
    . $IDF_PATH/export.sh && \
    ./install.sh

# ** note: we may need to modify the entrypoint.sh file below to include the esp-matter export.sh
RUN echo "source /opt/esp/esp-matter/export.sh > /dev/null 2>&1" >> ~/.bashrc

#############################
# Back to orginal Dockerfile
```

**??** When it completed (and each time I open the VSCode Container), it showed the following in the Output tab. Not sure if its relevant?
```
[2/18/2023, 7:08:27 AM] Unable to resolve configuration with compilerPath "C:\Espressif\esp32\tools\riscv32-esp-elf\esp-2021r2-patch5-8.4.0\riscv32-esp-elf\bin\riscv32-esp-elf-gcc.exe".  Using "/opt/esp/esp-matter/connectedhomeip/connectedhomeip/.environment/cipd/packages/arm/bin/arm-none-eabi-gcc" instead.
[2/18/2023, 7:08:27 AM] Unable to resolve configuration with compilerPath "C:\Espressif\esp32\tools\riscv32-esp-elf\esp-2021r2-patch5-8.4.0\riscv32-esp-elf\bin\riscv32-esp-elf-gcc.exe".  Using "/opt/esp/esp-matter/connectedhomeip/connectedhomeip/.environment/cipd/packages/arm/bin/arm-none-eabi-gcc" instead.
```

When I tried to build the `light` sample, I get
```
-- Building ESP-IDF components for target esp32c3
CMake Error at /opt/esp/idf/tools/cmake/build.cmake:452 (message):
Call Stack (most recent call first):
  /opt/esp/idf/tools/cmake/project.cmake:384 (idf_build_process)
  CMakeLists.txt:8 (project)
```

I modified the `devcontainer.json` file to point to the correct python path.
```
//		"idf.pythonBinPath": "/opt/esp/python_env/idf5.1_py3.8_env/bin/python",
		"idf.pythonBinPath": "/opt/esp/python_env/idf4.4_py3.8_env/bin/python",
```

🎉🥳
This time (after having to delete the `managed_components` folder in `/workspaces` - this is new..?) I was able to compile.


Do I need to modify the default `entrypoint.sh`, even though they were added via `source` in the `Dockerfile`? It currently contains. It compiled OK without any modifications...
```
#!/usr/bin/env bash
set -e

. $IDF_PATH/export.sh

exec "$@"
```

Is this the correct/best way of creating a new ESP Matter project in VSCode Docker Container? Or is there a better way?

**Comment by mriksman** [comment]
Given that it built OK, what would modifying the `entrypoint.sh` do? Fix the errors that appear in the Output log when opening the VSCode Container?

I'm away again for 18 days, and will try when I am back on my PC.

**Comment by shubhamdp** [comment]
This just sets up the required stuff to run esp-matter. As sourcing $IDF_PATH/export.sh is necessary before building any IDF application, similarly sourcing esp-matter/export.sh is necessary for building any esp-matter examples. That's the reason I suggested that you add one more line there.

**Comment by dhrishi** [comment]
I am closing this now. Please re-open in case of any issue
