### ISSUE TITLE
IDF efuse issue (CON-226)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#181]
Can you send this off to the IDF people?

I believe this is because BitString was renamed to BitStream in Python 3.7+. I am using 3.10.
I edited my IDF tree to do the rename and everything works.

jonsmirl@ares:~/aosp/esp-matter/examples/lowpan$ configure_esp_secure_cert.py -p /dev/ttyACM0 --keep_ds_data_on_host --efuse_key_id 1 --ca-cert cacert.pem --device-cert client.crt --private-key client.key --target_chip esp32c3 --secure_cert_type cust_flash_tlv --configure_ds
Traceback (most recent call last):
  File "/home/jonsmirl/esp/esp-idf/components/esptool_py/esptool/espefuse.py", line 15, in <module>
    import espressif.efuse.esp32 as esp32_efuse
  File "/home/jonsmirl/esp/esp-idf/components/esptool_py/esptool/espressif/efuse/esp32/__init__.py", line 1, in <module>
    from . import operations
  File "/home/jonsmirl/esp/esp-idf/components/esptool_py/esptool/espressif/efuse/esp32/operations.py", line 18, in <module>
    from . import fields
  File "/home/jonsmirl/esp/esp-idf/components/esptool_py/esptool/espressif/efuse/esp32/fields.py", line 17, in <module>
    from .. import base_fields
  File "/home/jonsmirl/esp/esp-idf/components/esptool_py/esptool/espressif/efuse/base_fields.py", line 14, in <module>
    from bitstring import BitArray, BitString, CreationError
ImportError: cannot import name 'BitString' from 'bitstring' (/home/jonsmirl/.espressif/python_env/idf4.4_py3.10_env/lib/python3.10/site-packages/bitstring.py)

**Comment by dhrishi** [comment]
@jonsmirl The fix for this (https://github.com/espressif/esp-idf/blob/release/v4.4/requirements.txt#L40) is not in IDF v4.4.3 release. It will be a part of v4.4.4 that will be out soon. Till that time, on your side, can you execute:
`pip install "bitstring>=3.1.6,<4"`
