### ISSUE TITLE
How to safely install multiple IDF vesions in Linux which doesn't impact projects running with existing IDF versions ? (CON-394)

### ISSUE THREAD

**Issue by aggaddam** [espressif/esp-matter#303]
Hi, 

I have few projects running on ESP-IDF v4.x.x and also have projects running on ESP-IDF v5.x.x. When I ran the ./install.sh file it overwrites in.espressif folder under the root directory.

After installing v5.x.x IDF version, when I try to set the environment for the project that runs with IDFv4.x.x using export.sh, I got the below error

`Detecting the Python interpreter
Checking "python" ...
Python 3.10.6
"python" has been detected
Adding ESP-IDF tools to PATH...
Traceback (most recent call last):
  File "/home/agaddam/Documents/irb_v207_new_fs/targets/simplifi/irb/li_esp32_sdk/esp-idf/tools/idf_tools.py", line 1860, in <module>
    main(sys.argv[1:])
  File "/home/agaddam/Documents/irb_v207_new_fs/targets/simplifi/irb/li_esp32_sdk/esp-idf/tools/idf_tools.py", line 1856, in main
    action_func(args)
  File "/home/agaddam/Documents/irb_v207_new_fs/targets/simplifi/irb/li_esp32_sdk/esp-idf/tools/idf_tools.py", line 1177, in action_export
    tools_info = filter_tools_info(tools_info)
  File "/home/agaddam/Documents/irb_v207_new_fs/targets/simplifi/irb/li_esp32_sdk/esp-idf/tools/idf_tools.py", line 1119, in filter_tools_info
    targets = get_user_defined_targets()
  File "/home/agaddam/Documents/irb_v207_new_fs/targets/simplifi/irb/li_esp32_sdk/esp-idf/tools/idf_tools.py", line 1099, in get_user_defined_targets
    if env == idf_env_json['idfSelectedId']:
KeyError: 'idfSelectedId'
`

**Comment by dhrishi** [comment]
Please create an issue in the [esp-idf repository](https://github.com/espressif/esp-idf) for better assistance.

I will close the issue here.
