### ISSUE TITLE
ModuleNotFoundError: No module named 'lark' (CON-456)

### ISSUE THREAD

**Issue by arpitsahu00740** [espressif/esp-matter#357]
I want to add matter light to my code, i am referring the light example of esp-matter sdk. On following i have made the changes to the CMakeLists(attached file) and copied the zap-generated folder, but i am getting following error while building the project - 

Traceback (most recent call last):
  File "esp-matter/examples/phoenix/build/esp-idf/chip/../../../../../connectedhomeip/connectedhomeip/config/esp32/third_party/connectedhomeip/scripts/codegen.py", line 28, in <module>
    from idl.matter_idl_parser import CreateParser
  File "esp-matter/connectedhomeip/connectedhomeip/scripts/idl/matter_idl_parser.py", line 7, in <module>
    from lark import Lark
ModuleNotFoundError: No module named 'lark'
[CMakeLists.txt](https://github.com/espressif/esp-matter/files/11358650/CMakeLists.txt)

**Comment by dhrishi** [comment]
Please refer the FAQs https://docs.espressif.com/projects/esp-matter/en/latest/esp32/faq.html#a1-8-modulenotfounderror-no-module-named-lark
