### ISSUE TITLE
【Error】 ERROR at //build/config/linux/pkg_config.gni:116:17: Script returned non-zero exit code.     pkgresult = exec_script(pkg_config_script, args, "value") (CON-469)

### ISSUE THREAD

**Issue by kurisaW** [espressif/esp-matter#368]
How can I solve this problem?

The first time I tried to run the./install.sh command, I got the following error:

```c
  Building wheel for pycryptodome (setup.py): started
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for pycryptodome (setup.py): finished with status 'error'
  ERROR: Failed building wheel for pycryptodome
  Running setup.py clean for pycryptodome
  Building wheel for gevent (pyproject.toml): started
```
So I tried to fix this by installing the necessary dependencies for the system using: `sudo apt install build-essential python3-dev`

But a new error occurs：
```c
ERROR at //build/config/linux/pkg_config.gni:116:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /home/kurisaw/Desktop/esp/esp-matter/connectedhomeip/connectedhomeip/.environment/gn_out/
Command: python3 /home/kurisaw/Desktop/esp/esp-matter/connectedhomeip/connectedhomeip/build/config/linux/pkg-config.py glib-2.0 gio-unix-2.0
Returned 1.
stderr:

Could not run pkg-config.

See //build/chip/linux/BUILD.gn:19:1: whence it was called.
pkg_config("glib") {
^-------------------
See //build/chip/linux/gdbus_library.gni:99:7: which caused the file to be included.
      glib_config,
      ^----------
['gn', 'gen', '/home/kurisaw/Desktop/esp/esp-matter/connectedhomeip/connectedhomeip/.environment/gn_out', '--args=chip_crypto="boringssl" dir_pigweed="/home/kurisaw/Desktop/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo"']

Traceback (most recent call last):
  File "/home/kurisaw/Desktop/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 335, in install_packages
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gn', 'gen', '/home/kurisaw/Desktop/esp/esp-matter/connectedhomeip/connectedhomeip/.environment/gn_out', '--args=chip_crypto="boringssl" dir_pigweed="/home/kurisaw/Desktop/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo"']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kurisaw/Desktop/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 857, in <module>
    sys.exit(main())
  File "/home/kurisaw/Desktop/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 849, in main
    return EnvSetup(**vars(parse())).setup()
  File "/home/kurisaw/Desktop/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 501, in setup
    result = step(spin)
  File "/home/kurisaw/Desktop/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 661, in virtualenv
    if not virtualenv_setup.install(
  File "/home/kurisaw/Desktop/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 370, in install
    install_packages(gn_target)
  File "/home/kurisaw/Desktop/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 343, in install_packages
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['gn', 'gen', '/home/kurisaw/Desktop/esp/esp-matter/connectedhomeip/connectedhomeip/.environment/gn_out', '--args=chip_crypto="boringssl" dir_pigweed="/home/kurisaw/Desktop/esp/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo"']' returned non-zero exit status 1.
```

**Comment by kurisaW** [comment]
This issue has been resolved and all you need to do is install the following dependencies:

```c
sudo apt install build-essential python3-dev

sudo apt-get install pkg-config

sudo apt-get install libglib2.0-dev libglib2.0-dev-bin libgio2.0-cil-dev
```
