### ISSUE TITLE
Mysterious Error 773 failure (CON-699)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#575]
Why did this commissioning attempt fail?  Is the ArmFailSafe(0) in packet 171810197 normal? 

Chip error 32 is CHIP_ERROR_TIMEOUT. So why did the Android side send ArmFailSafe (0s)?
~~~
I (94987) chip[EM]: >>> [E:54882r S:42077 M:171810197] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
I (94987) esp_matter_command: Received command 0x00000000 for endpoint 0x0000's cluster 0x00000030
I (94987) chip[FS]: GeneralCommissioning: Received ArmFailSafe (0s)
I (94987) chip[FS]: Fail-safe timer expired
I (94997) chip[EM]: <<< [E:54882r S:42077 M:24204685 (Ack:171810197)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
I (94997) chip[IN]: (S) Sending msg 24204685 on secure session with LSID: 42077
E (94997) chip[SVR]: Failsafe timer expired
I (94997) chip[SC]: SecureSession[0x3fc9d5b8, LSID:42077]: State change 'kActive' --> 'kPendingEviction'
E (94997) chip[SVR]: Commissioning failed (attempt 1): 32
~~~

On ESP
~~~
I (93947) chip[DL]: NVS set: chip-config/reg-location = 0 (0x0)
I (93957) chip[DL]: NVS set: chip-config/country-code = "XX"
I (93957) esp_matter_attribute: ********** W : Endpoint 0x0000's Cluster 0x00000030's Attribute 0x00000000 is 5 **********
I (93957) ep: app_attribute_update_cb type 0 priv 0x0
I (93957) ep: app_attribute_update_cb type 1 priv 0x0
I (93957) chip[EM]: <<< [E:54877r S:42077 M:24204678 (Ack:171810186)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
I (93957) chip[IN]: (S) Sending msg 24204678 on secure session with LSID: 42077
I (93957) chip[EM]: >>> [E:54876r S:42077 M:171810187 (Ack:24204677)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
I (94047) chip[EM]: >>> [E:54878r S:42077 M:171810188] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
I (94047) esp_matter_command: Received command 0x00000002 for endpoint 0x0000's cluster 0x0000003E
I (94047) chip[ZCL]: OpCreds: Certificate Chain request received for PAI
I (94057) chip[EM]: <<< [E:54878r S:42077 M:24204679 (Ack:171810188)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
I (94057) chip[IN]: (S) Sending msg 24204679 on secure session with LSID: 42077
I (94057) chip[EM]: >>> [E:54877r S:42077 M:171810189 (Ack:24204678)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
I (94147) chip[EM]: >>> [E:54879r S:42077 M:171810190] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
I (94147) esp_matter_command: Received command 0x00000002 for endpoint 0x0000's cluster 0x0000003E
I (94157) chip[ZCL]: OpCreds: Certificate Chain request received for DAC
I (94157) chip[EM]: <<< [E:54879r S:42077 M:24204680 (Ack:171810190)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
I (94157) chip[IN]: (S) Sending msg 24204680 on secure session with LSID: 42077
I (94157) chip[EM]: >>> [E:54878r S:42077 M:171810191 (Ack:24204679)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
I (94167) chip[EM]: >>> [E:54880r S:42077 M:171810192] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
I (94177) esp_matter_command: Received command 0x00000000 for endpoint 0x0000's cluster 0x0000003E
I (94177) chip[ZCL]: OpCreds: Received an AttestationRequest command
I (94177) chip[EM]: <<< [E:54880r S:42077 M:24204681 (Ack:171810192)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
I (94177) chip[IN]: (S) Sending msg 24204681 on secure session with LSID: 42077
I (94227) chip[ZCL]: OpCreds: AttestationRequest successful.
I (94227) chip[EM]: <<< [E:54880r S:42077 M:24204682 (Ack:171810192)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
I (94227) chip[IN]: (S) Sending msg 24204682 on secure session with LSID: 42077
I (94237) chip[EM]: >>> [E:54879r S:42077 M:171810193 (Ack:24204680)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
I (94357) chip[EM]: >>> [E:54881r S:42077 M:171810194] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
I (94357) esp_matter_command: Received command 0x00000004 for endpoint 0x0000's cluster 0x0000003E
I (94357) chip[ZCL]: OpCreds: Received a CSRRequest command
I (94357) chip[EM]: <<< [E:54881r S:42077 M:24204683 (Ack:171810194)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
I (94357) chip[IN]: (S) Sending msg 24204683 on secure session with LSID: 42077
I (94447) chip[ZCL]: OpCreds: AllocatePendingOperationalKey succeeded
I (94497) chip[ZCL]: OpCreds: CSRRequest successful.
I (94497) chip[EM]: <<< [E:54881r S:42077 M:24204684 (Ack:171810194)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
I (94507) chip[IN]: (S) Sending msg 24204684 on secure session with LSID: 42077
I (94507) chip[EM]: >>> [E:54880r S:42077 M:171810195 (Ack:24204682)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
I (94667) chip[EM]: >>> [E:54881r S:42077 M:171810196 (Ack:24204684)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
I (94987) chip[EM]: >>> [E:54882r S:42077 M:171810197] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
I (94987) esp_matter_command: Received command 0x00000000 for endpoint 0x0000's cluster 0x00000030
I (94987) chip[FS]: GeneralCommissioning: Received ArmFailSafe (0s)
I (94987) chip[FS]: Fail-safe timer expired
I (94997) chip[EM]: <<< [E:54882r S:42077 M:24204685 (Ack:171810197)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
I (94997) chip[IN]: (S) Sending msg 24204685 on secure session with LSID: 42077
E (94997) chip[SVR]: Failsafe timer expired
I (94997) chip[SC]: SecureSession[0x3fc9d5b8, LSID:42077]: State change 'kActive' --> 'kPendingEviction'
E (94997) chip[SVR]: Commissioning failed (attempt 1): 32
I (94997) chip[DIS]: Updating services using commissioning mode 2
I (94997) chip[DIS]: CHIP minimal mDNS started advertising.
I (95007) chip[DIS]: Advertise operational node 4284C2F5A80B5F7C-429B84E567D8EC6F
I (95007) chip[DIS]: CHIP minimal mDNS configured as 'Operational device'; instance name: 4284C2F5A80B5F7C-429B84E567D8EC6F.
I (95007) chip[DIS]: mDNS service published: _matter._tcp
I (95007) chip[DIS]: Advertise commission parameter vendorID=65522 productID=32769 discriminator=3452/13 cm=2
I (95017) chip[DIS]: CHIP minimal mDNS configured as 'Commissionable node device'; instance name: 756EF33CEAAB2638.
I (95027) chip[DIS]: mDNS service published: _matterc._udp
E (95027) chip[ZCL]: OpCreds: Got FailSafeTimerExpired
E (95027) chip[ZCL]: OpCreds: Proceeding to FailSafeCleanup on fail-safe expiry!
I (95027) chip[TS]: Pending Last Known Good Time: 2023-08-09T00:00:00
I (95027) chip[TS]: Previous Last Known Good Time: 2023-08-09T00:00:00
I (95027) chip[TS]: Reverted Last Known Good Time to previous value
I (95027) esp_matter_attribute: ********** W : Endpoint 0x0000's Cluster 0x00000030's Attribute 0x00000000 is 0 **********
I (95027) ep: app_attribute_update_cb type 0 priv 0x0
I (95027) ep: app_attribute_update_cb type 1 priv 0x0
I (95027) ep: Commissioning failed, fail safe timer expired
I (95027) chip[FS]: Fail-safe cleanly disarmed
I (95027) ep: Commissioning window opened
I (100597) app_main: Free internal 46472 biggest block 26624 total 46472
~~~

On Android side:
~~~
2023-08-16 16:07:26.226  9271-9348  CTL                     com.lowpan.m2                        D  Commissioning stage next step: 'AttestationVerification' -> 'SendOpCertSigningRequest'
2023-08-16 16:07:26.226  9271-9348  CTL                     com.lowpan.m2                        D  Performing next commissioning step 'SendOpCertSigningRequest'
2023-08-16 16:07:26.226  9271-9348  CTL                     com.lowpan.m2                        D  Sending CSR request to 0xb4000071243b7868 device
2023-08-16 16:07:26.226  9271-9348  DMG                     com.lowpan.m2                        D  ICR moving to [AddingComm]
2023-08-16 16:07:26.226  9271-9348  DMG                     com.lowpan.m2                        D  ICR moving to [AddedComma]
2023-08-16 16:07:26.227  9271-9348  EM                      com.lowpan.m2                        D  <<< [E:54881i S:37276 M:171810194] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
2023-08-16 16:07:26.227  9271-9348  IN                      com.lowpan.m2                        D  (S) Sending msg 171810194 on secure session with LSID: 37276
2023-08-16 16:07:26.227  9271-9348  DMG                     com.lowpan.m2                        D  ICR moving to [CommandSen]
2023-08-16 16:07:26.227  9271-9348  CTL                     com.lowpan.m2                        D  Sent CSR request, waiting for the CSR
2023-08-16 16:07:26.227  9271-9348  DMG                     com.lowpan.m2                        D  ICR moving to [AwaitingDe]
2023-08-16 16:07:26.227  9271-9348  EM                      com.lowpan.m2                        D  <<< [E:54880i S:37276 M:171810195 (Ack:24204682)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-08-16 16:07:26.227  9271-9348  IN                      com.lowpan.m2                        D  (S) Sending msg 171810195 on secure session with LSID: 37276
2023-08-16 16:07:26.228  9271-9348  EM                      com.lowpan.m2                        D  Flushed pending ack for MessageCounter:24204682 on exchange 54880i
2023-08-16 16:07:26.289  9271-9348  EM                      com.lowpan.m2                        D  >>> [E:54881i S:37276 M:24204683 (Ack:171810194)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-08-16 16:07:26.290  9271-9348  EM                      com.lowpan.m2                        D  Found matching exchange: 54881i, Delegate: 0xb40000712461a508
2023-08-16 16:07:26.290  9271-9348  EM                      com.lowpan.m2                        D  Rxd Ack; Removing MessageCounter:171810194 from Retrans Table on exchange 54881i
2023-08-16 16:07:26.435  9271-9348  EM                      com.lowpan.m2                        D  >>> [E:54881i S:37276 M:24204684 (Ack:171810194)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
2023-08-16 16:07:26.435  9271-9348  EM                      com.lowpan.m2                        D  Found matching exchange: 54881i, Delegate: 0xb40000712461a508
2023-08-16 16:07:26.435  9271-9348  EM                      com.lowpan.m2                        D  CHIP MessageCounter:171810194 not in RetransTable on exchange 54881i
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  ICR moving to [ResponseRe]
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  InvokeResponseMessage =
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  {
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  	suppressResponse = false, 
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  	InvokeResponseIBs =
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  	[
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  		InvokeResponseIB =
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  		{
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  			CommandDataIB =
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  			{
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  				CommandPathIB =
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  				{
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  					EndpointId = 0x0,
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  					ClusterId = 0x3e,
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  					CommandId = 0x5,
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  				},
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  				
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  				CommandFields = 
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  				{
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  					0x0 = [
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  							0x15, 0x30, 0x01, 0xcd, 0x30, 0x81, 0xca, 0x30, 0x70, 0x02, 0x01, 0x00, 0x30, 0x0e, 0x31, 0x0c, 0x30, 0x0a, 0x06, 0x03, 0x55, 0x04, 0x0a, 0x0c, 0x03, 0x43, 0x53, 0x52, 0x30, 0x59, 0x30, 0x13, 0x06, 0x07, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02, 0x01, 0x
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  					] (245 bytes)
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  					0x1 = [
2023-08-16 16:07:26.435  9271-9348  DMG                     com.lowpan.m2                        D  							0x26, 0x94, 0xe7, 0xf0, 0x90, 0xdf, 0x6f, 0x50, 0xdf, 0xa1, 0xfb, 0xca, 0x7a, 0x12, 0x87, 0x91, 0x00, 0x7f, 0x5a, 0x09, 0x49, 0x2e, 0xca, 0xfb, 0x54, 0x0f, 0xc4, 0x03, 0x80, 0xb3, 0x36, 0x82, 0x0d, 0xf7, 0xdc, 0x88, 0xca, 0x35, 0x07, 0x5d, 0x1e, 0x
2023-08-16 16:07:26.436  9271-9348  DMG                     com.lowpan.m2                        D  					] (64 bytes)
2023-08-16 16:07:26.436  9271-9348  DMG                     com.lowpan.m2                        D  				},
2023-08-16 16:07:26.436  9271-9348  DMG                     com.lowpan.m2                        D  			},
2023-08-16 16:07:26.436  9271-9348  DMG                     com.lowpan.m2                        D  			
2023-08-16 16:07:26.436  9271-9348  DMG                     com.lowpan.m2                        D  		},
2023-08-16 16:07:26.436  9271-9348  DMG                     com.lowpan.m2                        D  		
2023-08-16 16:07:26.436  9271-9348  DMG                     com.lowpan.m2                        D  	],
2023-08-16 16:07:26.436  9271-9348  DMG                     com.lowpan.m2                        D  	
2023-08-16 16:07:26.436  9271-9348  DMG                     com.lowpan.m2                        D  	InteractionModelRevision = 1
2023-08-16 16:07:26.436  9271-9348  DMG                     com.lowpan.m2                        D  },
2023-08-16 16:07:26.436  9271-9348  DMG                     com.lowpan.m2                        D  Received Command Response Data, Endpoint=0 Cluster=0x0000_003E Command=0x0000_0005
2023-08-16 16:07:26.436  9271-9348  CTL                     com.lowpan.m2                        D  Received certificate signing request from the device
2023-08-16 16:07:26.437  9271-9348  BaseCompletionListener  com.lowpan.m2                        D  onCommissioningStatusUpdate nodeId [2545594102198618759]  stage [SendOpCertSigningRequest]  errorCode [0]
2023-08-16 16:07:26.437  9271-9348  BaseCompletionListener  com.lowpan.m2                        D  onCommissioningStatusUpdate nodeId [2545594102198618759]  stage [SendOpCertSigningRequest]  errorCode [0]
2023-08-16 16:07:26.438  9271-9348  CTL                     com.lowpan.m2                        D  Successfully finished commissioning step 'SendOpCertSigningRequest'
2023-08-16 16:07:26.438  9271-9348  CTL                     com.lowpan.m2                        D  Commissioning stage next step: 'SendOpCertSigningRequest' -> 'ValidateCSR'
2023-08-16 16:07:26.438  9271-9348  CTL                     com.lowpan.m2                        D  Performing next commissioning step 'ValidateCSR'
2023-08-16 16:07:26.479  9271-9348  BaseCompletionListener  com.lowpan.m2                        D  onCommissioningStatusUpdate nodeId [2545594102198618759]  stage [ValidateCSR]  errorCode [0]
2023-08-16 16:07:26.479  9271-9348  BaseCompletionListener  com.lowpan.m2                        D  onCommissioningStatusUpdate nodeId [2545594102198618759]  stage [ValidateCSR]  errorCode [0]
2023-08-16 16:07:26.480  9271-9348  CTL                     com.lowpan.m2                        D  Successfully finished commissioning step 'ValidateCSR'
2023-08-16 16:07:26.480  9271-9348  CTL                     com.lowpan.m2                        D  Commissioning stage next step: 'ValidateCSR' -> 'GenerateNOCChain'
2023-08-16 16:07:26.480  9271-9348  CTL                     com.lowpan.m2                        D  Performing next commissioning step 'GenerateNOCChain'
2023-08-16 16:07:26.480  9271-9348  CTL                     com.lowpan.m2                        D  Getting certificate chain for the device from the issuer
2023-08-16 16:07:26.480  9271-9348  CTL                     com.lowpan.m2                        D  Parsing Certificate Signing Request
2023-08-16 16:07:26.515  9271-9348  TOO                     com.lowpan.m2                        D  VerifyCertificateSigningRequest
2023-08-16 16:07:26.520  9271-9348  DMG                     com.lowpan.m2                        D  ICR moving to [AwaitingDe]
2023-08-16 16:07:26.521  9271-9348  EM                      com.lowpan.m2                        D  <<< [E:54881i S:37276 M:171810196 (Ack:24204684)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-08-16 16:07:26.521  9271-9348  IN                      com.lowpan.m2                        D  (S) Sending msg 171810196 on secure session with LSID: 37276
2023-08-16 16:07:26.521  9271-9348  EM                      com.lowpan.m2                        D  Flushed pending ack for MessageCounter:24204684 on exchange 54881i
2023-08-16 16:07:26.602  9271-9774  TrafficStats            com.lowpan.m2                        D  tagSocket(126) with statsTag=0xffffffff, statsUid=-1
2023-08-16 16:07:26.785  9271-9271  CTL                     com.lowpan.m2                        D  setNOCChain() called
2023-08-16 16:07:26.786  9271-9271  CTL                     com.lowpan.m2                        D  Received callback from the CA for NOC Chain generation. Status src/controller/java/CHIPDeviceController-JNI.cpp:246: Success
2023-08-16 16:07:26.786  9271-9271  BaseCompletionListener  com.lowpan.m2                        D  onCommissioningStatusUpdate nodeId [2545594102198618759]  stage [GenerateNOCChain]  errorCode [0]
2023-08-16 16:07:26.787  9271-9271  BaseCompletionListener  com.lowpan.m2                        D  onCommissioningStatusUpdate nodeId [2545594102198618759]  stage [GenerateNOCChain]  errorCode [0]
2023-08-16 16:07:26.787  9271-9271  CTL                     com.lowpan.m2                        D  Successfully finished commissioning step 'GenerateNOCChain'
2023-08-16 16:07:26.787  9271-9271  CTL                     com.lowpan.m2                        D  Expiring failsafe on proxy 0xb4000071243b7868
2023-08-16 16:07:26.787  9271-9271  DMG                     com.lowpan.m2                        D  ICR moving to [AddingComm]
2023-08-16 16:07:26.787  9271-9271  DMG                     com.lowpan.m2                        D  ICR moving to [AddedComma]
2023-08-16 16:07:26.787  9271-9271  EM                      com.lowpan.m2                        D  <<< [E:54882i S:37276 M:171810197] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
2023-08-16 16:07:26.787  9271-9271  IN                      com.lowpan.m2                        D  (S) Sending msg 171810197 on secure session with LSID: 37276
2023-08-16 16:07:26.788  9271-9271  DMG                     com.lowpan.m2                        D  ICR moving to [CommandSen]
2023-08-16 16:07:26.789  9271-9271  ChipClient...hainIssuer com.lowpan.m2                        D  NOCChainGenerated Error 0
2023-08-16 16:07:26.790  9271-9271  ChipClient...hainIssuer com.lowpan.m2                        D  NOCChainGenerated Error 0
2023-08-16 16:07:26.941  9271-9348  EM                      com.lowpan.m2                        D  >>> [E:54882i S:37276 M:24204685 (Ack:171810197)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
2023-08-16 16:07:26.941  9271-9348  EM                      com.lowpan.m2                        D  Found matching exchange: 54882i, Delegate: 0xb40000712461bd08
2023-08-16 16:07:26.941  9271-9348  EM                      com.lowpan.m2                        D  Rxd Ack; Removing MessageCounter:171810197 from Retrans Table on exchange 54882i
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  ICR moving to [ResponseRe]
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  InvokeResponseMessage =
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  {
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  	suppressResponse = false, 
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  	InvokeResponseIBs =
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  	[
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  		InvokeResponseIB =
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  		{
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  			CommandDataIB =
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  			{
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  				CommandPathIB =
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  				{
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  					EndpointId = 0x0,
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  					ClusterId = 0x30,
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  					CommandId = 0x1,
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  				},
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  				
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  				CommandFields = 
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  				{
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  					0x0 = 0, 
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  					0x1 = "" (0 chars), 
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  				},
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  			},
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  			
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  		},
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  		
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  	],
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  	
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  	InteractionModelRevision = 1
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  },
2023-08-16 16:07:26.941  9271-9348  DMG                     com.lowpan.m2                        D  Received Command Response Data, Endpoint=0 Cluster=0x0000_0030 Command=0x0000_0001
2023-08-16 16:07:26.941  9271-9348  CTL                     com.lowpan.m2                        D  Failsafe disarmed
2023-08-16 16:07:26.943  9271-9348  BaseCompletionListener  com.lowpan.m2                        D  onCommissioningStatusUpdate nodeId [2545594102198618759]  stage [Cleanup]  errorCode [0]
2023-08-16 16:07:26.944  9271-9348  BaseCompletionListener  com.lowpan.m2                        D  onCommissioningStatusUpdate nodeId [2545594102198618759]  stage [Cleanup]  errorCode [0]
2023-08-16 16:07:26.944  9271-9348  CTL                     com.lowpan.m2                        D  Successfully finished commissioning step 'Cleanup'
2023-08-16 16:07:26.945  9271-9348  BaseCompletionListener  com.lowpan.m2                        D  onCommissioningComplete(): nodeId [2545594102198618759] errorCode [773]
2023-08-16 16:07:26.946  9271-9348  BaseCompletionListener  com.lowpan.m2                        D  onCommissioningComplete(): nodeId [2545594102198618759] errorCode [773]
2023-08-16 16:07:26.948  9271-9348  IN                      com.lowpan.m2                        D  SecureSession[0xb4000071ad19d590]: MarkForEviction Type:1 LSID:37276
2023-08-16 16:07:26.948  9271-9348  SC                      com.lowpan.m2                        D  SecureSession[0xb4000071ad19d590, LSID:37276]: State change 'kActive' --> 'kPendingEviction'
2023-08-16 16:07:26.948  9271-9348  EM                      com.lowpan.m2                        E  Failed to send Solitary ack for MessageCounter:24204685 on exchange 54882i:src/messaging/ExchangeContext.cpp:144: CHIP Error 0x00000002: Connection aborted
2023-08-16 16:07:26.948  9271-9348  DMG                     com.lowpan.m2                        D  ICR moving to [AwaitingDe]
2023-08-16 16:07:26.948  9271-9348  IN                      com.lowpan.m2                        D  SecureSession[0xb4000071ad19d590]: Released - Type:1 LSID:37276
2023-08-16 16:07:26.950  9271-9271  AppCommiss...gRequested com.lowpan.m2                        E  onCommissioningRequested() failed
                                                                                                    java.lang.IllegalStateException: Commissioning failed with error code [773]
                                                                                                    	at com.lowpan.m2.chip.ChipClient$awaitCommissionDevice$2$1.onCommissioningComplete(ChipClient.kt:361)
                                                                                                    	at chip.devicecontroller.ChipDeviceController.onCommissioningComplete(ChipDeviceController.java:365)
2023-08-16 16:07:26.952  9271-9271  AppCommiss...gRequested com.lowpan.m2                        E  onCommissioningRequested() failed
                                                                                                    java.lang.IllegalStateException: Commissioning failed with error code [773]
                                                                                                    	at com.lowpan.m2.chip.ChipClient$awaitCommissionDevice$2$1.onCommissioningComplete(ChipClient.kt:361)
                                                                                                    	at chip.devicecontroller.ChipDeviceController.onCommissioningComplete(ChipDeviceController.java:365)
2023-08-16 16:07:26.959  9271-9271  AppCommiss...gRequested com.lowpan.m2                        D  Commissioning: commissioningServiceDelegate.sendCommissioningError() succeeded
2023-08-16 16:07:26.960  9271-9271  AppCommiss...gRequested com.lowpan.m2                        D  Commissioning: commissioningServiceDelegate.sendCommissioningError() succeeded
2023-08-16 16:07:28.812  9271-9348  EM                      com.lowpan.m2                        D  >>> [E:39780r S:37273 M:110903214] (S) Msg RX from 14:AB0DE00000000009 [46E5] --- Type 0001:05 (IM:ReportData)
2023-08-16 16:07:28.812  9271-9348  EM                      com.lowpan.m2                        D  Handling via exchange: 39780r, Delegate: 0x71050ced48
2023-08-16 16:07:28.812  9271-9348  DMG                     com.lowpan.m2                        D  ReportDataMessage =
2023-08-16 16:07:28.812  9271-9348  DMG                     com.lowpan.m2                        D  {
2023-08-16 16:07:28.812  9271-9348  DMG                     com.lowpan.m2                        D  	SubscriptionId = 0x83d79115,
2023-08-16 16:07:28.812  9271-9348  DMG                     com.lowpan.m2                        D  	InteractionModelRevision = 1
2023-08-16 16:07:28.812  9271-9348  DMG                     com.lowpan.m2                        D  }
2023-08-16 16:07:28.812  9271-9348  DMG                     com.lowpan.m2                        D  Refresh LivenessCheckTime for 9224 milliseconds with SubscriptionId = 0x83d79115 Peer = 0e:AB0DE00000000009
~~~

**Comment by jonsmirl** [comment]
I believe I found the problem. I was using random numbers for my certificate serial numbers. Sometimes those numbers were negative. OpenSSL does not consider this an error and let me generate the certificates.  However, mbed SSL does flag it as an error. If you go read the x509 spec, the spec says they have to be positive.  So 773, 0x305 was the real error. This also explains why it would work on a retry. 50/50 the serial number was negative.

What was very confusing was how this error did not show up until the onCommissioningComplete() command

**Comment by jonsmirl** [comment]
We can close this, hopefully anyone getting error 773 can find this issue. This was a difficult issue to debug.
