### ISSUE TITLE
mfg_tool fails to generate a bin (CON-816)

### ISSUE THREAD

**Issue by maenkai** [espressif/esp-matter#673]
**Describe the bug**
The problem occurred when I pulled up the latest esp-matter repository, and everything was fine until I updated esp-matter

```shell
~/esp/esp-matter/tools/mfg_tool/mfg_tool.py  -cn "My bulb" --vendor-name "lipro" --product-name "E3P1" -v 0x1460 -p 0x8844 --pai -c PAI/Lipro-Chip-PAI-0x1460-Cert.pem -cd CD/Chip-CD-0x1460-0x8844.der --dac-key DAC/Lipro-Chip-DAC-0x1460-0x8844-Key.pem --dac-cert DAC/Lipro-Chip-DAC-0x1460-0x8844-Cert.pem --discovery-mode 2
```
result:
```shell
[2023-10-07 14:46:05,083] [   INFO] - Number of manufacturing NVS images to generate: 1
[2023-10-07 14:46:05,109] [   INFO] - Generating Config CSV...
[2023-10-07 14:46:05,109] [   INFO] - Writing chip manifest CSV header...
[2023-10-07 14:46:05,120] [   INFO] - Generated PAI certificate in DER format: out/1460_8844/staging/pai_cert.der
[2023-10-07 14:46:05,120] [   INFO] - Using DAC from command line arguments...
[2023-10-07 14:46:05,120] [   INFO] - DAC Certificate: DAC/Lipro-Chip-DAC-0x1460-0x8844-Cert.pem
[2023-10-07 14:46:05,120] [   INFO] - DAC Private Key: DAC/Lipro-Chip-DAC-0x1460-0x8844-Key.pem
[2023-10-07 14:46:05,121] [   INFO] - Generated DAC certificate in DER format: out/1460_8844/6d429540-1b3f-44be-9e33-12252243c311/internal/DAC_cert.der
[2023-10-07 14:46:05,121] [   INFO] - Generated DAC private key in binary format: out/1460_8844/6d429540-1b3f-44be-9e33-12252243c311/internal/DAC_private_key.bin
[2023-10-07 14:46:05,121] [   INFO] - Generated DAC public key in binary format: out/1460_8844/6d429540-1b3f-44be-9e33-12252243c311/internal/DAC_public_key.bin
Traceback (most recent call last):
  File "/home/mek/esp/esp-matter/tools/mfg_tool/mfg_tool.py", line 717, in <module>
    main()
  File "/home/mek/esp/esp-matter/tools/mfg_tool/mfg_tool.py", line 710, in main
    write_per_device_unique_data(args)
  File "/home/mek/esp/esp-matter/tools/mfg_tool/mfg_tool.py", line 378, in write_per_device_unique_data
    append_cn_dac_to_csv(UUIDs[int(row['Index'])], os.sep.join([OUT_DIR['top'], UUIDs[int(row['Index'])], "internal", "DAC_cert.pem"]))
  File "/home/mek/esp/esp-matter/tools/mfg_tool/mfg_tool.py", line 327, in append_cn_dac_to_csv
    with open(cert_path, 'r') as device_cert_file:
FileNotFoundError: [Errno 2] No such file or directory: 'out/1460_8844/6d429540-1b3f-44be-9e33-12252243c311/internal/DAC_cert.pem'
```

**Environment**
- ESP-Matter Commit Id:2832857748b46ddf3fa2fe42a902822298e26bda
- ESP-IDF Commit Id: e088c3766ba440e72268b458a68f27b6e7d63986
- SoC (eg: ESP32 or ESP32-C3): ESP32
- Device Logs (Please attach the log file):null
- Host Machine OS: ubuntu22.04
- Commissioner app and versions if present:null
- Commissioner's logs if present:null

**Any additional details**
I tried the following to fix the problem, but it didn't work!
```shell
cd  connectedhomeip/connectedhomei
rm .environment/ -fr
cd esp-matter
./install.sh
. ./export.sh
```

**Comment by shripad621git** [comment]
@maenkai , looking at the error log, it seems that the error you are encountering is a `FileNotFoundError`.Please make sure you provide the `correct path to dac-cert` as the above error is associated with it.
```
FileNotFoundError: [Errno 2] No such file or directory: 'out/1460_8844/6d429540-1b3f-44be-9e33-12252243c311/internal/DAC_cert.pem'
```
