### ISSUE TITLE
When I git the esp-matter from "https://github.com/espressif/esp-matter",I can't git all (CON-848)

### ISSUE THREAD

**Issue by tianrongqin** [espressif/esp-matter#699]
the error:
子模组路径 'third_party/qpg_sdk/repo'：检出 '6c3303e51559123a76d9e93ef902d57fc8302c32'
fatal: 远程错误：upload-pack: not our ref 2ba59bf969e94a0544e73e501d876722790f7a89
fatal: 获取了子模组路径 'third_party/silabs/gecko_sdk'，但是它没有包含 2ba59bf969e94a0544e73e501d876722790f7a89。直接获取该提交失败。
fatal:

How can I do to solve this program?

**Comment by tianrongqin** [comment]
Because the above program,when I carry "./install.sh" in the esp-matter,the error:
ERROR at //build/config/linux/pkg_config.gni:116:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /home/tianrq/esp-matter/connectedhomeip/connectedhomeip/.environment/gn_out/
Command: python3 /home/tianrq/esp-matter/connectedhomeip/connectedhomeip/build/config/linux/pkg-config.py glib-2.0 gio-unix-2.0
Returned 1.
stderr:

Could not run pkg-config.

See //build/chip/linux/BUILD.gn:19:1: whence it was called.
pkg_config("glib") {
^-------------------
See //build/chip/linux/gdbus_library.gni:106:7: which caused the file to be included.
      glib_config,
      ^----------
['gn', 'gen', '/home/tianrq/esp-matter/connectedhomeip/connectedhomeip/.environment/gn_out', '--args=chip_crypto="boringssl" dir_pigweed="/home/tianrq/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo"']

Traceback (most recent call last):
  File "/home/tianrq/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 392, in install_packages
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gn', 'gen', '/home/tianrq/esp-matter/connectedhomeip/connectedhomeip/.environment/gn_out', '--args=chip_crypto="boringssl" dir_pigweed="/home/tianrq/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo"']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tianrq/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 974, in <module>
    sys.exit(main())
  File "/home/tianrq/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 966, in main
    return EnvSetup(**vars(parse())).setup()
  File "/home/tianrq/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 573, in setup
    result = step(spin)
  File "/home/tianrq/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 762, in virtualenv
    if not virtualenv_setup.install(
  File "/home/tianrq/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 433, in install
    install_packages(gn_target)
  File "/home/tianrq/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 400, in install_packages
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['gn', 'gen', '/home/tianrq/esp-matter/connectedhomeip/connectedhomeip/.environment/gn_out', '--args=chip_crypto="boringssl" dir_pigweed="/home/tianrq/esp-matter/connectedhomeip/connectedhomeip/third_party/pigweed/repo"']' returned non-zero exit status 1.

**Comment by tianrongqin** [comment]
What should I do if the sub-module download fails during the download process?

**Comment by tianrongqin** [comment]
I carry "git submodule update --init" in esp-matter/connectedhomeip/connectedhomeip,but it also can't git.
