### ISSUE TITLE
Moving files to their final destination failure creating build esp32 matter (CON-919)

### ISSUE THREAD

**Issue by dave-code-ruiz** [espressif/esp-matter#759]
I have same problem like #527 

I think i cant solved it with Open a Powershell Admin window beause problem is in docker devcontainer.

I try changed it in docker container but i found this unsolved issue in docker for windows and mac: https://github.com/docker/for-win/issues/6369

Some option to solved it temporally while docker issue is resolved?

**Environment**
- command: /bin/bash -l -c scripts/run_in_build_env.sh './scripts/build/build_examples.py --target esp32-devkitc-lock build'
- Visual Studio Code Development in Windows - wsl2 - docker enviroment describe here: https://github.com/project-chip/connectedhomeip/blob/master/docs/VSCODE_DEVELOPMENT.md
- ESP-Matter Commit Id:
- ESP-IDF Commit Id:
- SoC (eg: ESP32 or ESP32-C3): ESP32

- Host Machine OS: Windows 10
- Commissioner app and versions if present:
- Commissioner's logs if present:
- ERROR:   failed to install fuchsia/third_party/armgcc/linux-amd64 in "arm": adding files to the site root: lstat /workspaces/connectedhomeip/.environment/cipd/packages/.cipd/pkgs/0/9z1FnQUHn-LGwcPNIsxnZzTE3HjoopYzwWlK3f1-HG0C/share/doc/gdb/qMemTags.html: no such file or directory
/workspaces/connectedhomeip/.environment/cipd/cipd ensure -ensure-file /workspaces/connectedhomeip/.environment/cipd/packages.ensure -root /workspaces/connectedhomeip/.environment/cipd/packages -log-level debug -json-output /workspaces/connectedhomeip/.environment/cipd/packages.json -max-threads 0 -cache-dir /home/vscode/.cipd-cache-dir
- Device Logs (Please attach the log file): 
[P89868 18:25:00.841 deployer.go:388 I] [unzip 11/12] Moving files to their final destination...
[P89868 18:26:09.584 deployer.go:403 I] [unzip 11/12] Cleaning up...
[P89868 18:26:09.988 deployer.go:409 I] [unzip 11/12] Deployed fuchsia/third_party/sysroot/linux:MaxMWDVheaJZkZTMeb2ROWBDQxtqdU050EZnJG-5qyUC in 88.2s
Errors:
  failed to install fuchsia/third_party/armgcc/linux-amd64 in "arm": adding files to the site root: lstat /workspaces/connectedhomeip/.environment/cipd/packages/.cipd/pkgs/0/9z1FnQUHn-LGwcPNIsxnZzTE3HjoopYzwWlK3f1-HG0C/share/doc/gdb/qMemTags.html: no such file or directory
/workspaces/connectedhomeip/.environment/cipd/cipd ensure -ensure-file /workspaces/connectedhomeip/.environment/cipd/packages.ensure -root /workspaces/connectedhomeip/.environment/cipd/packages -log-level debug -json-output /workspaces/connectedhomeip/.environment/cipd/packages.json -max-threads 0 -cache-dir /home/vscode/.cipd-cache-dir

None
Traceback (most recent call last):
  File "/workspaces/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 982, in <module>
    sys.exit(main())
  File "/workspaces/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 974, in main
    return EnvSetup(**vars(parse())).setup()
  File "/workspaces/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 573, in setup
    result = step(spin)
  File "/workspaces/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 686, in cipd
    if not cipd_update.update(
  File "/workspaces/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/update.py", line 384, in update
    subprocess.check_call(cmd, stdout=outs, stderr=subprocess.STDOUT)
  File "/home/vscode/pigweed/env/cipd/packages/python38/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/workspaces/connectedhomeip/.environment/cipd/cipd', 'ensure', '-ensure-file', '/workspaces/connectedhomeip/.environment/cipd/packages.ensure', '-root', '/workspaces/connectedhomeip/.environment/cipd/packages', '-log-level', 'debug', '-json-output', '/workspaces/connectedhomeip/.environment/cipd/packages.json', '-max-threads', '0', '-cache-dir', '/home/vscode/.cipd-cache-dir']' returned non-zero exit status 1.
Installing pip requirements for all...

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
Executing in build environment: 
bash: -c: option requires an argument

**Comment by dave-code-ruiz** [comment]
ok, i could solve this issue

I open a powershell with admin privil. and exec command for did folder casesensitive, it is needed it for all subfolders created in windows, in my case:

fsutil file SetCaseSensitiveInfo c:\Matter enable
fsutil file SetCaseSensitiveInfo C:\Matter\connectedhomeip enable

fsutil file SetCaseSensitiveInfo C:\Matter\connectedhomeip\.environment\cipd\packages\arm\share\doc\gdb\ enable
(last not needed if you exec the other two before create .enviroment folder)

After that, you can test folders creating in docker devcontainer two files, for example, /workspaces/connectedhomeip/Hello.txt and /workspaces/connectedhomeip/hello.txt

thanks
