### ISSUE TITLE
How do I increase the partition for my app (CON-1050)

### ISSUE THREAD

**Issue by i-kratko** [espressif/esp-matter#842]
Hello, I am building a Matter app for my ESP32-C6 that is based off the light example. I have added extra functionality and from logs i see when the code gets uploaded I see that the memory is exceeded and the ESP crashes. I don't really know a lot about partition tables and have a couple of questions.

From what i see the ota partitions split a large chunk of the memory into two even parts and if I am not mistaken this is a guarantee that an over the air update would be successful. 

Based on the partitioning table how should I edit it to increase the area in the memory where my app is stored.

Here is how the partitioning table looks right now.

```
esp_secure_cert,  0x3F, ,0xd000,    0x2000, encrypted
nvs,      data, nvs,     0x10000,   0xC000,
nvs_keys, data, nvs_keys,,          0x1000, encrypted
otadata,  data, ota,     ,          0x2000
phy_init, data, phy,     ,          0x1000,
ota_0,    app,  ota_0,   0x20000,   0x1E0000,
ota_1,    app,  ota_1,   0x200000,  0x1E0000,
fctry,    data, nvs,     0x3E0000,  0x6000
```

**Comment by i-kratko** [comment]
I figured I need to add additional information. I changed the partitions table, it complied, flashed onto the controller but the error persists.

Here is the new partitions table:

```
esp_secure_cert,  0x3F, ,0xd000,    0x2000, encrypted
nvs,      data, nvs,     0x10000,   0xC000,
nvs_keys, data, nvs_keys,,          0x1000, encrypted
otadata,  data, ota,     ,          0x2000
phy_init, data, phy,     ,          0x1000,
ota_0,    app,  ota_0,   0x20000,   0x3C0000,
fctry,    data, nvs,     0x3E0000,  0x6000

```
Here is the log from the terminal when the error occurs:

```
SPIWP:0xee
mode:DIO, clock div:2
load:0x4086c410,len:0xd4c
load:0x4086e610,len:0x2dd0
load:0x40875728,len:0x17d0
entry 0x4086c410
I (26) boot: ESP-IDF v5.1.2 2nd stage bootloader
I (27) boot: compile time Feb 15 2024 08:57:21
I (28) boot: chip revision: v0.0
I (30) boot.esp32c6: SPI Speed      : 80MHz
I (34) boot.esp32c6: SPI Mode       : DIO
I (39) boot.esp32c6: SPI Flash Size : 4MB
I (44) boot: Enabling RNG early entropy source...
I (49) boot: Partition Table:
I (53) boot: ## Label            Usage          Type ST Offset   Length
I (60) boot:  0 esp_secure_cert  unknown          3f 06 0000d000 00002000
I (68) boot:  1 nvs              WiFi data        01 02 00010000 0000c000
I (75) boot:  2 nvs_keys         NVS keys         01 04 0001c000 00001000
I (83) boot:  3 otadata          OTA data         01 00 0001d000 00002000
I (90) boot:  4 phy_init         RF data          01 01 0001f000 00001000
I (97) boot:  5 ota_0            OTA app          00 10 00020000 003c0000
I (105) boot:  6 fctry            WiFi data        01 02 003e0000 00006000
I (113) boot: End of partition table
I (117) esp_image: segment 0: paddr=00020020 vaddr=42180020 size=47e90h (294544) map
I (245) esp_image: segment 1: paddr=00067eb8 vaddr=40800000 size=08160h ( 33120) load
I (262) esp_image: segment 2: paddr=00070020 vaddr=42000020 size=1778e8h (1538280) map
I (889) esp_image: segment 3: paddr=001e7910 vaddr=40808160 size=12c9ch ( 76956) load
I (926) esp_image: segment 4: paddr=001fa5b4 vaddr=4081ae00 size=037d8h ( 14296) load
I (934) esp_image: segment 5: paddr=001fdd94 vaddr=50000000 size=00004h (     4) load
I (947) boot: Loaded app from partition at offset 0x20000
I (948) boot: Disabling RNG early entropy source...
I (959) cpu_start: Unicore app
I (960) cpu_start: Pro cpu up.
W (969) clk: esp_perip_clk_init() has not been implemented yet
I (976) cpu_start: Pro cpu start user code
I (976) cpu_start: cpu freq: 160000000 Hz
I (976) cpu_start: Application information:
I (979) cpu_start: Project name:     light
I (984) cpu_start: App version:      1.0
I (988) cpu_start: Compile time:     Feb 14 2024 20:03:39
I (994) cpu_start: ELF file SHA256:  9b5f25e8aa83c0b4...
I (1000) cpu_start: ESP-IDF:          v5.1.2
I (1005) cpu_start: Min chip rev:     v0.0
I (1010) cpu_start: Max chip rev:     v0.99 
I (1015) cpu_start: Chip rev:         v0.0
I (1020) heap_init: Initializing. RAM available for dynamic allocation:
I (1027) heap_init: At 40838190 len 00044480 (273 KiB): D/IRAM
I (1034) heap_init: At 4087C610 len 00002F54 (11 KiB): STACK/DIRAM
I (1040) heap_init: At 50000004 len 00003FE4 (15 KiB): RTCRAM
I (1047) spi_flash: detected chip: generic
I (1052) spi_flash: flash io: dio
I (1057) sleep: Configure to isolate all GPIO pins in sleep state
I (1063) sleep: Enable automatic switching of GPIO sleep configuration
I (1070) coexist: coex firmware version: b6d5e8c
I (1075) coexist: coexist rom version 5b8dcfa
I (1080) app_start: Starting scheduler on CPU0
I (1085) main_task: Started on CPU0
I (1085) main_task: Calling app_main()
Guru Meditation Error: Core  0 panic'ed (Store access fault). Exception was unhandled.

Core  0 register dump:
Stack dump detected
MEPC    : 0x40030db2  RA      : 0x4200964c  SP      : 0x4083afd0  GP      : 0x4081b600  
0x40030db2: memset in ROM
0x4200964c: bh1750_sensor_init() at /home/osboxes/psihoto/danostane/light/main/app_driver.cpp:33

TP      : 0x407f4160  T0      : 0x40028192  T1      : 0x0000000f  T2      : 0xffffffff  
0x40028192: __retarget_lock_release_recursive in ROM

S0/FP   : 0x40837000  S1      : 0x00000000  A0      : 0x00000000  A1      : 0x00000000  
A2      : 0x0000000c  A3      : 0x00000020  A4      : 0x00000000  A5      : 0x00000000  
A6      : 0x00000001  A7      : 0x0000000a  S2      : 0x00000000  S3      : 0x4083b038  
S4      : 0x00000000  S5      : 0x00000000  S6      : 0x00000000  S7      : 0x00000000  
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000  
T3      : 0x00000000  T4      : 0x00000000  T5      : 0x00000000  T6      : 0x00000000  
MSTATUS : 0x00001881  MTVEC   : 0x40800001  MCAUSE  : 0x00000007  MTVAL   : 0x00000000  
0x40800001: _vector_table at ??:?

MHARTID : 0x00000000  


Backtrace:


0x40030db2 in ?? ()
#0  0x40030db2 in ?? ()
#1  0x4200964c in bh1750_sensor_init () at /home/osboxes/psihoto/danostane/light/main/app_driver.cpp:31
#2  0x00000000 in ?? ()
Backtrace stopped: frame did not save the PC
ELF file SHA256: 9b5f25e8aa83c0b4

Rebooting...
ESP-ROM:esp32c6-20220919
Build:Sep 19 2022
rst:0xc (SW_CPU),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x4001975a
0x4001975a: software_reset_cpu in ROM

```

If more additional information needs to be provided I will do so.

**Comment by i-kratko** [comment]
Ok this turned into a one sided conversation but the problem was the following: I wasn't paying much attention when transferring code from my non matter project and accidentally set the initialization of a sensor before the i2cdev. Hope someone finds this useful one day.
